import PageLayout from '../components/page-layout.component';

import '../styles/globals.scss'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <PageLayout>
                    {children}
                </PageLayout>
            </body>
        </html>
    );
}